speed_up:
  name: Speed Up
  description: Bump the WHF speed up by 1.
  target:
    entity:
      integration: airscape
      domain: fan
slow_down:
  name: Slow Down
  description: Bump the WHF speed down by 1.
  target:
    entity:
      integration: airscape
      domain: fan
turn_on_to_minimum:
  name: Turn Fan on to Minimum Speed
  description: Will turn on the fan and set to optional minimum speed defined during config flow setup
  target:
    entity:
      integration: airscape
      domain: fan